---
- name: Playbook to stop and remove all Docker related packages and file from hosts
  hosts: nodes
  gather_facts: false
  become: yes
  tasks:
    - name: Stop the Docker service
      ignore_errors: yes
      service:
        name: docker
        state: stopped

    - name: Remove the docker-ee package (enterprise)
      ignore_errors: yes
      apt:
        name: docker-ee
        state: absent

    - name: Remove the docker-ce package (community edition)
      ignore_errors: yes
      apt:
        name: docker-ce
        state: absent

    - name: Remove the base docker package
      ignore_errors: yes
      apt:
        name: docker
        state: absent

    - name: Delete the /var/lib/docker directory
      ignore_errors: yes
      file:
        path: /var/lib/docker
        state: absent
